[build]
  command = "pip install -r requirements.txt && mkdir -p netlify/functions"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.7"
  PIPENV_VENV_IN_PROJECT = "1"
  PIPENV_DEFAULT_PYTHON_VERSION = "3.7"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Add security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' https://xauusd-api.herokuapp.com;"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
