[build]
  base = "react-app"
  command = "npm install && npm run build"
  publish = "react-app/dist"

# Enable prerendering for better SEO
[build.environment]
  NODE_VERSION = "18"

# Force HTTPS redirect
[[redirects]]
  from = "http://xauusd-chart-live.com/*"
  to = "https://xauusd-chart-live.com/:splat"
  status = 301
  force = true

# Serve specific HTML files for each route (order matters - more specific first)
[[redirects]]
  from = "/about-us"
  to = "/about-us.html"
  status = 200
  force = false

[[redirects]]
  from = "/disclaimer"
  to = "/disclaimer.html"
  status = 200
  force = false

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy-policy.html"
  status = 200
  force = false

[[redirects]]
  from = "/terms-of-service"
  to = "/terms-of-service.html"
  status = 200
  force = false

# Handle trailing slashes
[[redirects]]
  from = "/about-us/"
  to = "/about-us.html"
  status = 200
  force = false

[[redirects]]
  from = "/disclaimer/"
  to = "/disclaimer.html"
  status = 200
  force = false

[[redirects]]
  from = "/privacy-policy/"
  to = "/privacy-policy.html"
  status = 200
  force = false

[[redirects]]
  from = "/terms-of-service/"
  to = "/terms-of-service.html"
  status = 200
  force = false

# Redirect all other routes to index.html for client-side routing (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Add security headers with HTTPS enforcement
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; font-src 'self' https:;"
