[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Force HTTPS and redirect www to non-www
[[redirects]]
  from = "http://xauusd-chart-live.com/*"
  to = "https://xauusd-chart-live.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.xauusd-chart-live.com/*"
  to = "https://xauusd-chart-live.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.xauusd-chart-live.com/*"
  to = "https://xauusd-chart-live.com/:splat"
  status = 301
  force = true

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables configuration
[build.environment]
  # The API URL will be set in the Netlify dashboard
  VITE_API_URL = "https://xauusd-api.herokuapp.com"

# Security headers for public usage
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' analytics.ahrefs.com www.googletagmanager.com; style-src 'self' 'unsafe-inline'; font-src 'self'; img-src 'self' data: www.googletagmanager.com; connect-src 'self' https://xauusd-api.herokuapp.com analytics.ahrefs.com www.googletagmanager.com www.google-analytics.com;"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
